### PR TITLE
fix some typos in mongo_stats.sh

### PR DESCRIPTION
**Pull request by firebus**
minor typo that probably doesn't affect anyone actually using this script :)

### CODE REVIEW

**Comment by toshok** [comment]
:man_facepalming: thanks for these fixes!  any more forthcoming or should I merge? :)

**Comment by firebus** [comment]
not sure! i'm just sort of bumbling along following https://honeycomb.io/docs/connect/mongodb/statistics/ :) i'll holler when i'm done for the day?

one thing I'm seeing is that when this script calls ``` var globalLocks = db.serverStatus().locks.Global.acquireCount;``` I get "Cannot read property 'acquireCount' of undefined" 

but that feels like maybe a configuration or other weirdness on my (mongo) end. did I mention that I have no idea what I'm doing here?

**Comment by firebus** [comment]
yeah - i get "Cannot read property 'acquireCount' in both the addGlobalLocks and addDatabaseLocks functions, and i can't get stats out unless I comment out those calls.

```
    //addGlobalLocks(newLocksData);
    //addDatabaseLocks(newLocksData);
```

but that feels more like a bug report where hopefully someone will explain the obvious thing i'm doing wrong, i'll file an issue for it. i think i'm done for now, thanks!

**Comment by emfree** [comment]
Thanks!! Are you running MongoDB 2.6? If so, #4 should address the "Cannot read property 'acquireCount'" issue; although the data from this script will be a little bare-bones as a result.

**Comment by paulosman** [comment]
Feels weird to merge a 3-year-old PR, but we're cleaning out backlogs and I can't see why _not_ to merge this. Thanks!

**Pull request merged**
